baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
publishDir = "docs"

title = "C42 Docs"
theme = "docdock"

[params]
editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
# themeStyle = "theme" # overide base css
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<h3>INTERACTIVE DOCS</h3>"
name = "<i class='fa fa-external-link'></i> Platform V2"
identifier = "tip"
url = "https://api.c42.io/swagger/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-external-link'></i> Platform V1"
url = "https://calendar42.com/api/docs/"
identifier = "v1"
weight = 30

[[menu.shortcuts]]
pre = "<h3>FIND US</h3>"
name = "<i class='fa fa-globe'></i> Calendar42.com"
url = "https://calendar42.com"
identifier = "website"
weight = 40

[[menu.shortcuts]]
name = "<i class='fa fa-github'></i> Github"
target = "_blank"
url = "https://github.com/calendar42"
identifier = "github"
weight = 41

[[menu.shortcuts]]
name = "<i class='fa fa-envelope-o'></i> Contact"
url = "mailto:ella@calendar42.com"
identifier = "contact"
weight = 42

[[menu.shortcuts]]
name = "<i class='fa fa-users'></i> Careers"
url = "careers.calendar42.com"
identifier = "careers"
weight = 43
